	double Ev_runNumber;
	double Ev_eventNumber;
	double Ev_lumiBlock;
	double Ev_numInteractionsBXm1;
	double Ev_numInteractionsBX0;
	double Ev_numInteractionsBXp1;
	double Ev_numPrimaryVertices;
	double Ev_puWeight;
	double Ev_MET;
	double Ev_METphi;
	int GT_NumGenTaus;
	vector<float>* GT_MomentumRank;
	vector<float>* GT_Pt;
	vector<float>* GT_Eta;
	vector<float>* GT_Phi;
	vector<float>* GT_VisPt;
	vector<float>* GT_VisEta;
	vector<float>* GT_VisPhi;
	vector<bool>* GT_ToElectron;
	vector<bool>* GT_ToMuon;
	vector<bool>* GT_ToHadrons;
	vector<int>* GT_ParentId;
	vector<float>* GT_ParentP;
	vector<float>* GT_ParentPt;
	vector<float>* GT_ParentEta;
	vector<float>* GT_ParentPhi;
	int GJ_NumGenJets;
	vector<float>* GJ_MomentumRank;
	vector<float>* GJ_Pt;
	vector<float>* GJ_Eta;
	vector<float>* GJ_Phi;
	vector<bool>* GJ_IsBjet;
	int T_NumTaus;
	vector<float>* T_MomentumRank;
	vector<float>* T_Pt;
	vector<float>* T_Eta;
	vector<float>* T_Phi;
	vector<unsigned int>* T_NProngs;
	vector<unsigned int>* T_NSignalGammas;
	vector<unsigned int>* T_NSignalNeutrals;
	vector<unsigned int>* T_DecayMode;
	vector<float>* T_EmFraction;
	vector<bool>* T_IsInTheCracks;
	vector<bool>* T_HPSagainstElectronLoose;
	vector<bool>* T_HPSagainstElectronMVA;
	vector<bool>* T_HPSagainstElectronMedium;
	vector<bool>* T_HPSagainstElectronTight;
	vector<bool>* T_HPSagainstMuonLoose;
	vector<bool>* T_HPSagainstMuonMedium;
	vector<bool>* T_HPSagainstMuonTight;
	vector<bool>* T_HPSbyLooseCombinedIsolationDeltaBetaCorr;
	vector<bool>* T_HPSbyMediumCombinedIsolationDeltaBetaCorr;
	vector<bool>* T_HPSbyTightCombinedIsolationDeltaBetaCorr;
	vector<bool>* T_HPSbyVLooseCombinedIsolationDeltaBetaCorr;
	vector<bool>* T_HPSdecayModeFinding;
	vector<float>* T_LTPt;
	vector<float>* T_Charge;
	vector<bool>* T_LTvalid;
	vector<float>* T_LTIpVtdxy;
	vector<float>* T_LTIpVtdz;
	vector<float>* T_LTIpVtdxyError;
	vector<float>* T_LTIpVtdzError;
	vector<float>* T_LTvx;
	vector<float>* T_LTvy;
	vector<float>* T_LTvz;
	vector<unsigned int>* T_LTValidHits;
	vector<float>* T_LTNormChiSqrd;
	vector<int>* T_TauGenMatchDaughter0Id;
	vector<int>* T_TauGenMatchDaughter1Id;
	vector<int>* T_TauGenMatchId;
	vector<int>* T_TauGenMatchMother0Id;
	vector<int>* T_TauGenMatchMother1Id;
	vector<int>* T_TauGenMatchGrandmother00Id;
	vector<int>* T_TauGenMatchGrandmother01Id;
	vector<int>* T_TauGenMatchGrandmother10Id;
	vector<int>* T_TauGenMatchGrandmother11Id;
	vector<int>* T_TauGenMatchDaughter0Status;
	vector<int>* T_TauGenMatchDaughter1Status;
	vector<int>* T_TauGenMatchStatus;
	vector<int>* T_TauGenMatchMother0Status;
	vector<int>* T_TauGenMatchMother1Status;
	vector<int>* T_TauGenMatchGrandmother00Status;
	vector<int>* T_TauGenMatchGrandmother01Status;
	vector<int>* T_TauGenMatchGrandmother10Status;
	vector<int>* T_TauGenMatchGrandmother11Status;
	int E_NumElectrons;
	vector<float>* E_MomentumRank;
	vector<float>* E_Pt;
	vector<float>* E_Eta;
	vector<float>* E_Phi;
	vector<bool>* E_IsTightElectron;
	vector<bool>* E_IsLooseElectron;
	vector<int>* E_ElectronGenMatchDaughter0Id;
	vector<int>* E_ElectronGenMatchDaughter1Id;
	vector<int>* E_ElectronGenMatchId;
	vector<int>* E_ElectronGenMatchMother0Id;
	vector<int>* E_ElectronGenMatchMother1Id;
	vector<int>* E_ElectronGenMatchGrandmother00Id;
	vector<int>* E_ElectronGenMatchGrandmother01Id;
	vector<int>* E_ElectronGenMatchGrandmother10Id;
	vector<int>* E_ElectronGenMatchGrandmother11Id;
	vector<int>* E_ElectronGenMatchDaughter0Status;
	vector<int>* E_ElectronGenMatchDaughter1Status;
	vector<int>* E_ElectronGenMatchStatus;
	vector<int>* E_ElectronGenMatchMother0Status;
	vector<int>* E_ElectronGenMatchMother1Status;
	vector<int>* E_ElectronGenMatchGrandmother00Status;
	vector<int>* E_ElectronGenMatchGrandmother01Status;
	vector<int>* E_ElectronGenMatchGrandmother10Status;
	vector<int>* E_ElectronGenMatchGrandmother11Status;
	int M_NumMuons;
	vector<float>* M_MomentumRank;
	vector<float>* M_Pt;
	vector<float>* M_Eta;
	vector<float>* M_Phi;
	vector<float>* M_RelIso;
	vector<bool>* M_IsTightMuon;
	vector<bool>* M_IsLooseMuon;
	vector<int>* M_MuonGenMatchDaughter0Id;
	vector<int>* M_MuonGenMatchDaughter1Id;
	vector<int>* M_MuonGenMatchId;
	vector<int>* M_MuonGenMatchMother0Id;
	vector<int>* M_MuonGenMatchMother1Id;
	vector<int>* M_MuonGenMatchGrandmother00Id;
	vector<int>* M_MuonGenMatchGrandmother01Id;
	vector<int>* M_MuonGenMatchGrandmother10Id;
	vector<int>* M_MuonGenMatchGrandmother11Id;
	vector<int>* M_MuonGenMatchDaughter0Status;
	vector<int>* M_MuonGenMatchDaughter1Status;
	vector<int>* M_MuonGenMatchStatus;
	vector<int>* M_MuonGenMatchMother0Status;
	vector<int>* M_MuonGenMatchMother1Status;
	vector<int>* M_MuonGenMatchGrandmother00Status;
	vector<int>* M_MuonGenMatchGrandmother01Status;
	vector<int>* M_MuonGenMatchGrandmother10Status;
	vector<int>* M_MuonGenMatchGrandmother11Status;
	int J_NumJets;
	vector<float>* J_MomentumRank;
	vector<float>* J_Pt;
	vector<float>* J_Eta;
	vector<float>* J_Phi;
	vector<float>* J_combSecVtxBTag;
	vector<bool>* J_combSecVtxLooseBTag;
	vector<bool>* J_combSecVtxMediumBTag;
	vector<bool>* J_combSecVtxTightBTag;
	unsigned int TTM_NumTaus;
	unsigned int TTM_NumMuons;
	unsigned int TTM_NumCombos;
	vector<unsigned int>* TTM_MomentumRank;
	vector<unsigned int>* TTM_Tau1MomentumRank;
	vector<float>* TTM_Tau1Pt;
	vector<float>* TTM_Tau1Eta;
	vector<float>* TTM_Tau1Phi;
	vector<unsigned int>* TTM_Tau1NProngs;
	vector<unsigned int>* TTM_Tau1NSignalGammas;
	vector<unsigned int>* TTM_Tau1NSignalNeutrals;
	vector<unsigned int>* TTM_Tau1DecayMode;
	vector<float>* TTM_Tau1EmFraction;
	vector<bool>* TTM_Tau1IsInTheCracks;
	vector<bool>* TTM_Tau1HPSagainstElectronLoose;
	vector<bool>* TTM_Tau1HPSagainstElectronMVA;
	vector<bool>* TTM_Tau1HPSagainstElectronMedium;
	vector<bool>* TTM_Tau1HPSagainstElectronTight;
	vector<bool>* TTM_Tau1HPSagainstMuonLoose;
	vector<bool>* TTM_Tau1HPSagainstMuonMedium;
	vector<bool>* TTM_Tau1HPSagainstMuonTight;
	vector<bool>* TTM_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau1HPSdecayModeFinding;
	vector<float>* TTM_Tau1LTPt;
	vector<float>* TTM_Tau1Charge;
	vector<bool>* TTM_Tau1LTvalid;
	vector<float>* TTM_Tau1LTIpVtdxy;
	vector<float>* TTM_Tau1LTIpVtdz;
	vector<float>* TTM_Tau1LTIpVtdxyError;
	vector<float>* TTM_Tau1LTIpVtdzError;
	vector<float>* TTM_Tau1LTvx;
	vector<float>* TTM_Tau1LTvy;
	vector<float>* TTM_Tau1LTvz;
	vector<unsigned int>* TTM_Tau1LTValidHits;
	vector<float>* TTM_Tau1LTNormChiSqrd;
	vector<int>* TTM_Tau1GenMatchDaughter0Id;
	vector<int>* TTM_Tau1GenMatchDaughter1Id;
	vector<int>* TTM_Tau1GenMatchId;
	vector<int>* TTM_Tau1GenMatchMother0Id;
	vector<int>* TTM_Tau1GenMatchMother1Id;
	vector<int>* TTM_Tau1GenMatchGrandmother00Id;
	vector<int>* TTM_Tau1GenMatchGrandmother01Id;
	vector<int>* TTM_Tau1GenMatchGrandmother10Id;
	vector<int>* TTM_Tau1GenMatchGrandmother11Id;
	vector<int>* TTM_Tau1GenMatchDaughter0Status;
	vector<int>* TTM_Tau1GenMatchDaughter1Status;
	vector<int>* TTM_Tau1GenMatchStatus;
	vector<int>* TTM_Tau1GenMatchMother0Status;
	vector<int>* TTM_Tau1GenMatchMother1Status;
	vector<int>* TTM_Tau1GenMatchGrandmother00Status;
	vector<int>* TTM_Tau1GenMatchGrandmother01Status;
	vector<int>* TTM_Tau1GenMatchGrandmother10Status;
	vector<int>* TTM_Tau1GenMatchGrandmother11Status;
	vector<unsigned int>* TTM_Tau2MomentumRank;
	vector<float>* TTM_Tau2Pt;
	vector<float>* TTM_Tau2Eta;
	vector<float>* TTM_Tau2Phi;
	vector<unsigned int>* TTM_Tau2NProngs;
	vector<unsigned int>* TTM_Tau2NSignalGammas;
	vector<unsigned int>* TTM_Tau2NSignalNeutrals;
	vector<unsigned int>* TTM_Tau2DecayMode;
	vector<float>* TTM_Tau2EmFraction;
	vector<bool>* TTM_Tau2IsInTheCracks;
	vector<bool>* TTM_Tau2HPSagainstElectronLoose;
	vector<bool>* TTM_Tau2HPSagainstElectronMVA;
	vector<bool>* TTM_Tau2HPSagainstElectronMedium;
	vector<bool>* TTM_Tau2HPSagainstElectronTight;
	vector<bool>* TTM_Tau2HPSagainstMuonLoose;
	vector<bool>* TTM_Tau2HPSagainstMuonMedium;
	vector<bool>* TTM_Tau2HPSagainstMuonTight;
	vector<bool>* TTM_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau2HPSdecayModeFinding;
	vector<float>* TTM_Tau2LTPt;
	vector<float>* TTM_Tau2Charge;
	vector<bool>* TTM_Tau2LTvalid;
	vector<float>* TTM_Tau2LTIpVtdxy;
	vector<float>* TTM_Tau2LTIpVtdz;
	vector<float>* TTM_Tau2LTIpVtdxyError;
	vector<float>* TTM_Tau2LTIpVtdzError;
	vector<float>* TTM_Tau2LTvx;
	vector<float>* TTM_Tau2LTvy;
	vector<float>* TTM_Tau2LTvz;
	vector<unsigned int>* TTM_Tau2LTValidHits;
	vector<float>* TTM_Tau2LTNormChiSqrd;
	vector<int>* TTM_Tau2GenMatchDaughter0Id;
	vector<int>* TTM_Tau2GenMatchDaughter1Id;
	vector<int>* TTM_Tau2GenMatchId;
	vector<int>* TTM_Tau2GenMatchMother0Id;
	vector<int>* TTM_Tau2GenMatchMother1Id;
	vector<int>* TTM_Tau2GenMatchGrandmother00Id;
	vector<int>* TTM_Tau2GenMatchGrandmother01Id;
	vector<int>* TTM_Tau2GenMatchGrandmother10Id;
	vector<int>* TTM_Tau2GenMatchGrandmother11Id;
	vector<int>* TTM_Tau2GenMatchDaughter0Status;
	vector<int>* TTM_Tau2GenMatchDaughter1Status;
	vector<int>* TTM_Tau2GenMatchStatus;
	vector<int>* TTM_Tau2GenMatchMother0Status;
	vector<int>* TTM_Tau2GenMatchMother1Status;
	vector<int>* TTM_Tau2GenMatchGrandmother00Status;
	vector<int>* TTM_Tau2GenMatchGrandmother01Status;
	vector<int>* TTM_Tau2GenMatchGrandmother10Status;
	vector<int>* TTM_Tau2GenMatchGrandmother11Status;
	vector<unsigned int>* TTM_MuonMomentumRank;
	vector<float>* TTM_MuonPt;
	vector<float>* TTM_MuonEta;
	vector<float>* TTM_MuonPhi;
	vector<float>* TTM_MuonRelIso;
	vector<int>* TTM_MuonIsLooseMuon;
	vector<int>* TTM_MuonIsTightMuon;
	vector<unsigned int>* TTM_NumOtherLooseMuons;
	vector<unsigned int>* TTM_NumOtherExLooseMuons;
	vector<unsigned int>* TTM_NumOtherTightMuons;
	unsigned int TTM_NumOtherLooseElectrons;
	unsigned int TTM_NumOtherExLooseElectrons;
	unsigned int TTM_NumOtherTightElectrons;
	vector<float>* TTM_LeptonEventWeight;
	vector<int>* TTM_MuonGenMatchDaughter0Id;
	vector<int>* TTM_MuonGenMatchDaughter1Id;
	vector<int>* TTM_MuonGenMatchId;
	vector<int>* TTM_MuonGenMatchMother0Id;
	vector<int>* TTM_MuonGenMatchMother1Id;
	vector<int>* TTM_MuonGenMatchGrandmother00Id;
	vector<int>* TTM_MuonGenMatchGrandmother01Id;
	vector<int>* TTM_MuonGenMatchGrandmother10Id;
	vector<int>* TTM_MuonGenMatchGrandmother11Id;
	vector<int>* TTM_MuonGenMatchDaughter0Status;
	vector<int>* TTM_MuonGenMatchDaughter1Status;
	vector<int>* TTM_MuonGenMatchStatus;
	vector<int>* TTM_MuonGenMatchMother0Status;
	vector<int>* TTM_MuonGenMatchMother1Status;
	vector<int>* TTM_MuonGenMatchGrandmother00Status;
	vector<int>* TTM_MuonGenMatchGrandmother01Status;
	vector<int>* TTM_MuonGenMatchGrandmother10Status;
	vector<int>* TTM_MuonGenMatchGrandmother11Status;
	vector<float>* TTM_DitauVisibleMass;
	vector<float>* TTM_DitauMETMass;
	vector<float>* TTM_DitauCosDeltaPhi;
	vector<float>* TTM_DitauDeltaR;
	vector<float>* TTM_Tau1MuonDeltaR;
	vector<float>* TTM_Tau2MuonDeltaR;
	vector<float>* TTM_HT;
	vector<unsigned int>* TTM_NumCSVLbtagJets;
	vector<unsigned int>* TTM_NumCSVMbtagJets;
	vector<unsigned int>* TTM_NumCSVTbtagJets;
	vector<unsigned int>* TTM_NumNonCSVLbtagJets;
	vector<unsigned int>* TTM_NumNonCSVMbtagJets;
	vector<unsigned int>* TTM_NumNonCSVTbtagJets;
