	Ev_runNumber = 0;
	Ev_eventNumber = 0;
	Ev_lumiBlock = 0;
	Ev_numInteractionsBXm1 = 0;
	Ev_numInteractionsBX0 = 0;
	Ev_numInteractionsBXp1 = 0;
	Ev_numPrimaryVertices = 0;
	Ev_puWeight = 0;
	Ev_MET = 0;
	Ev_METphi = 0;
	E_NumElectrons = 0;
	E_MomentumRank->clear();
	E_Pt->clear();
	E_Eta->clear();
	E_Phi->clear();
	E_IsTightElectron->clear();
	E_IsLooseElectron->clear();
	M_NumMuons = 0;
	M_MomentumRank->clear();
	M_Pt->clear();
	M_Eta->clear();
	M_Phi->clear();
	M_RelIso->clear();
	M_IsTightMuon->clear();
	M_IsLooseMuon->clear();
	J_NumJets = 0;
	J_MomentumRank->clear();
	J_Pt->clear();
	J_Eta->clear();
	J_Phi->clear();
	J_combSecVtxBTag->clear();
	J_combSecVtxLooseBTag->clear();
	J_combSecVtxMediumBTag->clear();
	J_combSecVtxTightBTag->clear();
	Test_LeadingJetPt = 0;
	Test_LeadingJetEta = 0;
	Test_LeadingJetPhi = 0;
	Test_PUweight = 0;
	Test_NumJets = 0;
	Test_NumCSVM = 0;
	Test_PassesTMLE = 0;
	Test_PassesTMTE = 0;
	Test_PassesLMTE = 0;
	Test_Trigger = 0;
