	double Ev_runNumber;
	double Ev_eventNumber;
	double Ev_lumiBlock;
	double Ev_puWeight;
	double Ev_puWeightUp;
	double Ev_puWeightDown;
	double Ev_topPtWeight;
	double Ev_topPtWeightUp;
	double Ev_topPtWeightDown;
	double Ev_q2WeightUp;
	double Ev_q2WeightDown;
	double Ev_MET;
	double Ev_METphi;
	bool Ev_IsTauEvent;
	double Ev_puWeight2012A;
	double Ev_puWeight2012B;
	double Ev_puWeight2012C;
	double Ev_puWeight2012D;
	double Ev_puWeight2012AB;
	double Ev_puWeight2012BC;
	double Ev_puWeight2012CD;
	double Ev_puWeight2012ABC;
	int V_NumVertices;
	double V_NumInteractionsBXm1;
	double V_NumInteractionsBX0;
	double V_NumInteractionsBXp1;
	std::vector<float>* V_Xcoord;
	std::vector<float>* V_XcoordErr;
	std::vector<float>* V_Ycoord;
	std::vector<float>* V_YcoordErr;
	std::vector<float>* V_Zcoord;
	std::vector<float>* V_ZcoordErr;
	std::vector<float>* V_Rho;
	std::vector<float>* V_NumDOF;
	std::vector<float>* V_NormChiSquared;
	int GT_NumGenTaus;
	std::vector<float>* GT_MomentumRank;
	std::vector<float>* GT_Pt;
	std::vector<float>* GT_Eta;
	std::vector<float>* GT_Phi;
	std::vector<float>* GT_VisPt;
	std::vector<float>* GT_VisEta;
	std::vector<float>* GT_VisPhi;
	std::vector<bool>* GT_ToElectron;
	std::vector<bool>* GT_ToMuon;
	std::vector<bool>* GT_ToHadrons;
	std::vector<int>* GT_ParentId;
	std::vector<float>* GT_ParentP;
	std::vector<float>* GT_ParentPt;
	std::vector<float>* GT_ParentEta;
	std::vector<float>* GT_ParentPhi;
	int GJ_NumGenJets;
	std::vector<float>* GJ_MomentumRank;
	std::vector<float>* GJ_Pt;
	std::vector<float>* GJ_Eta;
	std::vector<float>* GJ_Phi;
	std::vector<bool>* GJ_IsBjet;
	int T_NumTaus;
	std::vector<float>* T_MomentumRank;
	std::vector<float>* T_Pt;
	std::vector<float>* T_Eta;
	std::vector<float>* T_Phi;
	std::vector<unsigned int>* T_NProngs;
	std::vector<unsigned int>* T_NSignalGammas;
	std::vector<unsigned int>* T_NSignalNeutrals;
	std::vector<unsigned int>* T_DecayMode;
	std::vector<float>* T_EmFraction;
	std::vector<bool>* T_IsInTheCracks;
	std::vector<bool>* T_HPSagainstElectronDeadECAL;
	std::vector<bool>* T_HPSagainstElectronLoose;
	std::vector<bool>* T_HPSagainstElectronLooseMVA2;
	std::vector<bool>* T_HPSagainstElectronLooseMVA3;
	std::vector<bool>* T_HPSagainstElectronMVA;
	std::vector<bool>* T_HPSagainstElectronMVA2category;
	std::vector<float>* T_HPSagainstElectronMVA2raw;
	std::vector<bool>* T_HPSagainstElectronMVA3category;
	std::vector<float>* T_HPSagainstElectronMVA3raw;
	std::vector<bool>* T_HPSagainstElectronMedium;
	std::vector<bool>* T_HPSagainstElectronMediumMVA2;
	std::vector<bool>* T_HPSagainstElectronMediumMVA3;
	std::vector<bool>* T_HPSagainstElectronTight;
	std::vector<bool>* T_HPSagainstElectronTightMVA2;
	std::vector<bool>* T_HPSagainstElectronTightMVA3;
	std::vector<bool>* T_HPSagainstElectronVLooseMVA2;
	std::vector<bool>* T_HPSagainstElectronVTightMVA3;
	std::vector<bool>* T_HPSagainstMuonLoose;
	std::vector<bool>* T_HPSagainstMuonLoose2;
	std::vector<bool>* T_HPSagainstMuonMedium;
	std::vector<bool>* T_HPSagainstMuonMedium2;
	std::vector<bool>* T_HPSagainstMuonTight;
	std::vector<bool>* T_HPSagainstMuonTight2;
	std::vector<float>* T_HPSbyCombinedIsolationDeltaBetaCorrRaw;
	std::vector<float>* T_HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
	std::vector<float>* T_HPSbyIsolationMVA2raw;
	std::vector<bool>* T_HPSbyLooseCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* T_HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* T_HPSbyLooseIsolationMVA;
	std::vector<bool>* T_HPSbyLooseIsolationMVA2;
	std::vector<bool>* T_HPSbyMediumCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* T_HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* T_HPSbyMediumIsolationMVA;
	std::vector<bool>* T_HPSbyMediumIsolationMVA2;
	std::vector<bool>* T_HPSbyTightCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* T_HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* T_HPSbyTightIsolationMVA;
	std::vector<bool>* T_HPSbyTightIsolationMVA2;
	std::vector<bool>* T_HPSbyVLooseCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* T_HPSdecayModeFinding;
	std::vector<float>* T_HPSbyIsolationMVAraw;
	std::vector<float>* T_LTPt;
	std::vector<float>* T_Charge;
	std::vector<bool>* T_LTvalid;
	std::vector<float>* T_LTIpVtdxy;
	std::vector<float>* T_LTIpVtdz;
	std::vector<float>* T_LTIpVtdxyError;
	std::vector<float>* T_LTIpVtdzError;
	std::vector<float>* T_LTvx;
	std::vector<float>* T_LTvy;
	std::vector<float>* T_LTvz;
	std::vector<unsigned int>* T_LTValidHits;
	std::vector<float>* T_LTNormChiSqrd;
	std::vector<int>* T_TauGenMatchDaughter0Id;
	std::vector<int>* T_TauGenMatchDaughter1Id;
	std::vector<int>* T_TauGenMatchId;
	std::vector<int>* T_TauGenMatchMother0Id;
	std::vector<int>* T_TauGenMatchMother1Id;
	std::vector<int>* T_TauGenMatchGrandmother00Id;
	std::vector<int>* T_TauGenMatchGrandmother01Id;
	std::vector<int>* T_TauGenMatchGrandmother10Id;
	std::vector<int>* T_TauGenMatchGrandmother11Id;
	std::vector<int>* T_TauGenMatchDaughter0Status;
	std::vector<int>* T_TauGenMatchDaughter1Status;
	std::vector<int>* T_TauGenMatchStatus;
	std::vector<int>* T_TauGenMatchMother0Status;
	std::vector<int>* T_TauGenMatchMother1Status;
	std::vector<int>* T_TauGenMatchGrandmother00Status;
	std::vector<int>* T_TauGenMatchGrandmother01Status;
	std::vector<int>* T_TauGenMatchGrandmother10Status;
	std::vector<int>* T_TauGenMatchGrandmother11Status;
	int E_NumElectrons;
	std::vector<float>* E_MomentumRank;
	std::vector<float>* E_Pt;
	std::vector<float>* E_Eta;
	std::vector<float>* E_Phi;
	std::vector<bool>* E_IsTightElectron;
	std::vector<bool>* E_IsLooseElectron;
	std::vector<int>* E_ElectronGenMatchDaughter0Id;
	std::vector<int>* E_ElectronGenMatchDaughter1Id;
	std::vector<int>* E_ElectronGenMatchId;
	std::vector<int>* E_ElectronGenMatchMother0Id;
	std::vector<int>* E_ElectronGenMatchMother1Id;
	std::vector<int>* E_ElectronGenMatchGrandmother00Id;
	std::vector<int>* E_ElectronGenMatchGrandmother01Id;
	std::vector<int>* E_ElectronGenMatchGrandmother10Id;
	std::vector<int>* E_ElectronGenMatchGrandmother11Id;
	std::vector<int>* E_ElectronGenMatchDaughter0Status;
	std::vector<int>* E_ElectronGenMatchDaughter1Status;
	std::vector<int>* E_ElectronGenMatchStatus;
	std::vector<int>* E_ElectronGenMatchMother0Status;
	std::vector<int>* E_ElectronGenMatchMother1Status;
	std::vector<int>* E_ElectronGenMatchGrandmother00Status;
	std::vector<int>* E_ElectronGenMatchGrandmother01Status;
	std::vector<int>* E_ElectronGenMatchGrandmother10Status;
	std::vector<int>* E_ElectronGenMatchGrandmother11Status;
	int M_NumMuons;
	std::vector<float>* M_MomentumRank;
	std::vector<float>* M_Pt;
	std::vector<float>* M_Eta;
	std::vector<float>* M_Phi;
	std::vector<float>* M_RelIso;
	std::vector<bool>* M_IsTightMuon;
	std::vector<bool>* M_IsLooseMuon;
	std::vector<int>* M_MuonGenMatchDaughter0Id;
	std::vector<int>* M_MuonGenMatchDaughter1Id;
	std::vector<int>* M_MuonGenMatchId;
	std::vector<int>* M_MuonGenMatchMother0Id;
	std::vector<int>* M_MuonGenMatchMother1Id;
	std::vector<int>* M_MuonGenMatchGrandmother00Id;
	std::vector<int>* M_MuonGenMatchGrandmother01Id;
	std::vector<int>* M_MuonGenMatchGrandmother10Id;
	std::vector<int>* M_MuonGenMatchGrandmother11Id;
	std::vector<int>* M_MuonGenMatchDaughter0Status;
	std::vector<int>* M_MuonGenMatchDaughter1Status;
	std::vector<int>* M_MuonGenMatchStatus;
	std::vector<int>* M_MuonGenMatchMother0Status;
	std::vector<int>* M_MuonGenMatchMother1Status;
	std::vector<int>* M_MuonGenMatchGrandmother00Status;
	std::vector<int>* M_MuonGenMatchGrandmother01Status;
	std::vector<int>* M_MuonGenMatchGrandmother10Status;
	std::vector<int>* M_MuonGenMatchGrandmother11Status;
	int J_NumJets;
	std::vector<float>* J_MomentumRank;
	std::vector<float>* J_Pt;
	std::vector<float>* J_Eta;
	std::vector<float>* J_Phi;
	std::vector<float>* J_combSecVtxBTag;
	std::vector<bool>* J_combSecVtxLooseBTag;
	std::vector<bool>* J_combSecVtxMediumBTag;
	std::vector<bool>* J_combSecVtxTightBTag;
	unsigned int TT_NumTaus;
	unsigned int TT_NumCombos;
	std::vector<unsigned int>* TT_MomentumRank;
	std::vector<unsigned int>* TT_Tau1MomentumRank;
	std::vector<float>* TT_Tau1Pt;
	std::vector<float>* TT_Tau1Eta;
	std::vector<float>* TT_Tau1Phi;
	std::vector<unsigned int>* TT_Tau1NProngs;
	std::vector<unsigned int>* TT_Tau1NSignalGammas;
	std::vector<unsigned int>* TT_Tau1NSignalNeutrals;
	std::vector<unsigned int>* TT_Tau1DecayMode;
	std::vector<float>* TT_Tau1EmFraction;
	std::vector<bool>* TT_Tau1IsInTheCracks;
	std::vector<bool>* TT_Tau1HPSagainstElectronDeadECAL;
	std::vector<bool>* TT_Tau1HPSagainstElectronLoose;
	std::vector<bool>* TT_Tau1HPSagainstElectronLooseMVA2;
	std::vector<bool>* TT_Tau1HPSagainstElectronLooseMVA3;
	std::vector<bool>* TT_Tau1HPSagainstElectronMVA;
	std::vector<bool>* TT_Tau1HPSagainstElectronMVA2category;
	std::vector<float>* TT_Tau1HPSagainstElectronMVA2raw;
	std::vector<bool>* TT_Tau1HPSagainstElectronMVA3category;
	std::vector<float>* TT_Tau1HPSagainstElectronMVA3raw;
	std::vector<bool>* TT_Tau1HPSagainstElectronMedium;
	std::vector<bool>* TT_Tau1HPSagainstElectronMediumMVA2;
	std::vector<bool>* TT_Tau1HPSagainstElectronMediumMVA3;
	std::vector<bool>* TT_Tau1HPSagainstElectronTight;
	std::vector<bool>* TT_Tau1HPSagainstElectronTightMVA2;
	std::vector<bool>* TT_Tau1HPSagainstElectronTightMVA3;
	std::vector<bool>* TT_Tau1HPSagainstElectronVLooseMVA2;
	std::vector<bool>* TT_Tau1HPSagainstElectronVTightMVA3;
	std::vector<bool>* TT_Tau1HPSagainstMuonLoose;
	std::vector<bool>* TT_Tau1HPSagainstMuonLoose2;
	std::vector<bool>* TT_Tau1HPSagainstMuonMedium;
	std::vector<bool>* TT_Tau1HPSagainstMuonMedium2;
	std::vector<bool>* TT_Tau1HPSagainstMuonTight;
	std::vector<bool>* TT_Tau1HPSagainstMuonTight2;
	std::vector<float>* TT_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw;
	std::vector<float>* TT_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
	std::vector<float>* TT_Tau1HPSbyIsolationMVA2raw;
	std::vector<bool>* TT_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TT_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TT_Tau1HPSbyLooseIsolationMVA;
	std::vector<bool>* TT_Tau1HPSbyLooseIsolationMVA2;
	std::vector<bool>* TT_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TT_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TT_Tau1HPSbyMediumIsolationMVA;
	std::vector<bool>* TT_Tau1HPSbyMediumIsolationMVA2;
	std::vector<bool>* TT_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TT_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TT_Tau1HPSbyTightIsolationMVA;
	std::vector<bool>* TT_Tau1HPSbyTightIsolationMVA2;
	std::vector<bool>* TT_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TT_Tau1HPSdecayModeFinding;
	std::vector<float>* TT_Tau1HPSbyIsolationMVAraw;
	std::vector<float>* TT_Tau1LTPt;
	std::vector<float>* TT_Tau1Charge;
	std::vector<bool>* TT_Tau1LTvalid;
	std::vector<float>* TT_Tau1LTIpVtdxy;
	std::vector<float>* TT_Tau1LTIpVtdz;
	std::vector<float>* TT_Tau1LTIpVtdxyError;
	std::vector<float>* TT_Tau1LTIpVtdzError;
	std::vector<float>* TT_Tau1LTvx;
	std::vector<float>* TT_Tau1LTvy;
	std::vector<float>* TT_Tau1LTvz;
	std::vector<unsigned int>* TT_Tau1LTValidHits;
	std::vector<float>* TT_Tau1LTNormChiSqrd;
	std::vector<int>* TT_Tau1GenMatchDaughter0Id;
	std::vector<int>* TT_Tau1GenMatchDaughter1Id;
	std::vector<int>* TT_Tau1GenMatchId;
	std::vector<int>* TT_Tau1GenMatchMother0Id;
	std::vector<int>* TT_Tau1GenMatchMother1Id;
	std::vector<int>* TT_Tau1GenMatchGrandmother00Id;
	std::vector<int>* TT_Tau1GenMatchGrandmother01Id;
	std::vector<int>* TT_Tau1GenMatchGrandmother10Id;
	std::vector<int>* TT_Tau1GenMatchGrandmother11Id;
	std::vector<int>* TT_Tau1GenMatchDaughter0Status;
	std::vector<int>* TT_Tau1GenMatchDaughter1Status;
	std::vector<int>* TT_Tau1GenMatchStatus;
	std::vector<int>* TT_Tau1GenMatchMother0Status;
	std::vector<int>* TT_Tau1GenMatchMother1Status;
	std::vector<int>* TT_Tau1GenMatchGrandmother00Status;
	std::vector<int>* TT_Tau1GenMatchGrandmother01Status;
	std::vector<int>* TT_Tau1GenMatchGrandmother10Status;
	std::vector<int>* TT_Tau1GenMatchGrandmother11Status;
	std::vector<unsigned int>* TT_Tau2MomentumRank;
	std::vector<float>* TT_Tau2Pt;
	std::vector<float>* TT_Tau2Eta;
	std::vector<float>* TT_Tau2Phi;
	std::vector<unsigned int>* TT_Tau2NProngs;
	std::vector<unsigned int>* TT_Tau2NSignalGammas;
	std::vector<unsigned int>* TT_Tau2NSignalNeutrals;
	std::vector<unsigned int>* TT_Tau2DecayMode;
	std::vector<float>* TT_Tau2EmFraction;
	std::vector<bool>* TT_Tau2IsInTheCracks;
	std::vector<bool>* TT_Tau2HPSagainstElectronDeadECAL;
	std::vector<bool>* TT_Tau2HPSagainstElectronLoose;
	std::vector<bool>* TT_Tau2HPSagainstElectronLooseMVA2;
	std::vector<bool>* TT_Tau2HPSagainstElectronLooseMVA3;
	std::vector<bool>* TT_Tau2HPSagainstElectronMVA;
	std::vector<bool>* TT_Tau2HPSagainstElectronMVA2category;
	std::vector<float>* TT_Tau2HPSagainstElectronMVA2raw;
	std::vector<bool>* TT_Tau2HPSagainstElectronMVA3category;
	std::vector<float>* TT_Tau2HPSagainstElectronMVA3raw;
	std::vector<bool>* TT_Tau2HPSagainstElectronMedium;
	std::vector<bool>* TT_Tau2HPSagainstElectronMediumMVA2;
	std::vector<bool>* TT_Tau2HPSagainstElectronMediumMVA3;
	std::vector<bool>* TT_Tau2HPSagainstElectronTight;
	std::vector<bool>* TT_Tau2HPSagainstElectronTightMVA2;
	std::vector<bool>* TT_Tau2HPSagainstElectronTightMVA3;
	std::vector<bool>* TT_Tau2HPSagainstElectronVLooseMVA2;
	std::vector<bool>* TT_Tau2HPSagainstElectronVTightMVA3;
	std::vector<bool>* TT_Tau2HPSagainstMuonLoose;
	std::vector<bool>* TT_Tau2HPSagainstMuonLoose2;
	std::vector<bool>* TT_Tau2HPSagainstMuonMedium;
	std::vector<bool>* TT_Tau2HPSagainstMuonMedium2;
	std::vector<bool>* TT_Tau2HPSagainstMuonTight;
	std::vector<bool>* TT_Tau2HPSagainstMuonTight2;
	std::vector<float>* TT_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw;
	std::vector<float>* TT_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
	std::vector<float>* TT_Tau2HPSbyIsolationMVA2raw;
	std::vector<bool>* TT_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TT_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TT_Tau2HPSbyLooseIsolationMVA;
	std::vector<bool>* TT_Tau2HPSbyLooseIsolationMVA2;
	std::vector<bool>* TT_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TT_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TT_Tau2HPSbyMediumIsolationMVA;
	std::vector<bool>* TT_Tau2HPSbyMediumIsolationMVA2;
	std::vector<bool>* TT_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TT_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TT_Tau2HPSbyTightIsolationMVA;
	std::vector<bool>* TT_Tau2HPSbyTightIsolationMVA2;
	std::vector<bool>* TT_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TT_Tau2HPSdecayModeFinding;
	std::vector<float>* TT_Tau2HPSbyIsolationMVAraw;
	std::vector<float>* TT_Tau2LTPt;
	std::vector<float>* TT_Tau2Charge;
	std::vector<bool>* TT_Tau2LTvalid;
	std::vector<float>* TT_Tau2LTIpVtdxy;
	std::vector<float>* TT_Tau2LTIpVtdz;
	std::vector<float>* TT_Tau2LTIpVtdxyError;
	std::vector<float>* TT_Tau2LTIpVtdzError;
	std::vector<float>* TT_Tau2LTvx;
	std::vector<float>* TT_Tau2LTvy;
	std::vector<float>* TT_Tau2LTvz;
	std::vector<unsigned int>* TT_Tau2LTValidHits;
	std::vector<float>* TT_Tau2LTNormChiSqrd;
	std::vector<int>* TT_Tau2GenMatchDaughter0Id;
	std::vector<int>* TT_Tau2GenMatchDaughter1Id;
	std::vector<int>* TT_Tau2GenMatchId;
	std::vector<int>* TT_Tau2GenMatchMother0Id;
	std::vector<int>* TT_Tau2GenMatchMother1Id;
	std::vector<int>* TT_Tau2GenMatchGrandmother00Id;
	std::vector<int>* TT_Tau2GenMatchGrandmother01Id;
	std::vector<int>* TT_Tau2GenMatchGrandmother10Id;
	std::vector<int>* TT_Tau2GenMatchGrandmother11Id;
	std::vector<int>* TT_Tau2GenMatchDaughter0Status;
	std::vector<int>* TT_Tau2GenMatchDaughter1Status;
	std::vector<int>* TT_Tau2GenMatchStatus;
	std::vector<int>* TT_Tau2GenMatchMother0Status;
	std::vector<int>* TT_Tau2GenMatchMother1Status;
	std::vector<int>* TT_Tau2GenMatchGrandmother00Status;
	std::vector<int>* TT_Tau2GenMatchGrandmother01Status;
	std::vector<int>* TT_Tau2GenMatchGrandmother10Status;
	std::vector<int>* TT_Tau2GenMatchGrandmother11Status;
	std::vector<float>* TT_DitauVisibleMass;
	std::vector<float>* TT_DitauMETMass;
	std::vector<float>* TT_DitauCosDeltaPhi;
	std::vector<float>* TT_DitauDeltaR;
	std::vector<float>* TT_HT;
	std::vector<unsigned int>* TT_NumCSVLbtagJets;
	std::vector<unsigned int>* TT_NumCSVMbtagJets;
	std::vector<unsigned int>* TT_NumCSVTbtagJets;
	std::vector<unsigned int>* TT_NumNonCSVLbtagJets;
	std::vector<unsigned int>* TT_NumNonCSVMbtagJets;
	std::vector<unsigned int>* TT_NumNonCSVTbtagJets;
	unsigned int TTL_NumTaus;
	unsigned int TTL_NumMuons;
	unsigned int TTL_NumElectrons;
	unsigned int TTL_NumLeptons;
	unsigned int TTL_NumCombos;
	std::vector<int>* TTL_MomentumRank;
	std::vector<int>* TTL_Tau1MomentumRank;
	std::vector<float>* TTL_Tau1Pt;
	std::vector<float>* TTL_Tau1Eta;
	std::vector<float>* TTL_Tau1Phi;
	std::vector<unsigned int>* TTL_Tau1NProngs;
	std::vector<unsigned int>* TTL_Tau1NSignalGammas;
	std::vector<unsigned int>* TTL_Tau1NSignalNeutrals;
	std::vector<unsigned int>* TTL_Tau1DecayMode;
	std::vector<float>* TTL_Tau1EmFraction;
	std::vector<bool>* TTL_Tau1IsInTheCracks;
	std::vector<bool>* TTL_Tau1HPSagainstElectronDeadECAL;
	std::vector<bool>* TTL_Tau1HPSagainstElectronLoose;
	std::vector<bool>* TTL_Tau1HPSagainstElectronLooseMVA2;
	std::vector<bool>* TTL_Tau1HPSagainstElectronLooseMVA3;
	std::vector<bool>* TTL_Tau1HPSagainstElectronMVA;
	std::vector<bool>* TTL_Tau1HPSagainstElectronMVA2category;
	std::vector<float>* TTL_Tau1HPSagainstElectronMVA2raw;
	std::vector<bool>* TTL_Tau1HPSagainstElectronMVA3category;
	std::vector<float>* TTL_Tau1HPSagainstElectronMVA3raw;
	std::vector<bool>* TTL_Tau1HPSagainstElectronMedium;
	std::vector<bool>* TTL_Tau1HPSagainstElectronMediumMVA2;
	std::vector<bool>* TTL_Tau1HPSagainstElectronMediumMVA3;
	std::vector<bool>* TTL_Tau1HPSagainstElectronTight;
	std::vector<bool>* TTL_Tau1HPSagainstElectronTightMVA2;
	std::vector<bool>* TTL_Tau1HPSagainstElectronTightMVA3;
	std::vector<bool>* TTL_Tau1HPSagainstElectronVLooseMVA2;
	std::vector<bool>* TTL_Tau1HPSagainstElectronVTightMVA3;
	std::vector<bool>* TTL_Tau1HPSagainstMuonLoose;
	std::vector<bool>* TTL_Tau1HPSagainstMuonLoose2;
	std::vector<bool>* TTL_Tau1HPSagainstMuonMedium;
	std::vector<bool>* TTL_Tau1HPSagainstMuonMedium2;
	std::vector<bool>* TTL_Tau1HPSagainstMuonTight;
	std::vector<bool>* TTL_Tau1HPSagainstMuonTight2;
	std::vector<float>* TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw;
	std::vector<float>* TTL_Tau1HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
	std::vector<float>* TTL_Tau1HPSbyIsolationMVA2raw;
	std::vector<bool>* TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TTL_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TTL_Tau1HPSbyLooseIsolationMVA;
	std::vector<bool>* TTL_Tau1HPSbyLooseIsolationMVA2;
	std::vector<bool>* TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TTL_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TTL_Tau1HPSbyMediumIsolationMVA;
	std::vector<bool>* TTL_Tau1HPSbyMediumIsolationMVA2;
	std::vector<bool>* TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TTL_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TTL_Tau1HPSbyTightIsolationMVA;
	std::vector<bool>* TTL_Tau1HPSbyTightIsolationMVA2;
	std::vector<bool>* TTL_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TTL_Tau1HPSdecayModeFinding;
	std::vector<float>* TTL_Tau1HPSbyIsolationMVAraw;
	std::vector<float>* TTL_Tau1LTPt;
	std::vector<float>* TTL_Tau1Charge;
	std::vector<bool>* TTL_Tau1LTvalid;
	std::vector<float>* TTL_Tau1LTIpVtdxy;
	std::vector<float>* TTL_Tau1LTIpVtdz;
	std::vector<float>* TTL_Tau1LTIpVtdxyError;
	std::vector<float>* TTL_Tau1LTIpVtdzError;
	std::vector<float>* TTL_Tau1LTvx;
	std::vector<float>* TTL_Tau1LTvy;
	std::vector<float>* TTL_Tau1LTvz;
	std::vector<unsigned int>* TTL_Tau1LTValidHits;
	std::vector<float>* TTL_Tau1LTNormChiSqrd;
	std::vector<int>* TTL_Tau1GenMatchDaughter0Id;
	std::vector<int>* TTL_Tau1GenMatchDaughter1Id;
	std::vector<int>* TTL_Tau1GenMatchId;
	std::vector<int>* TTL_Tau1GenMatchMother0Id;
	std::vector<int>* TTL_Tau1GenMatchMother1Id;
	std::vector<int>* TTL_Tau1GenMatchGrandmother00Id;
	std::vector<int>* TTL_Tau1GenMatchGrandmother01Id;
	std::vector<int>* TTL_Tau1GenMatchGrandmother10Id;
	std::vector<int>* TTL_Tau1GenMatchGrandmother11Id;
	std::vector<int>* TTL_Tau1GenMatchDaughter0Status;
	std::vector<int>* TTL_Tau1GenMatchDaughter1Status;
	std::vector<int>* TTL_Tau1GenMatchStatus;
	std::vector<int>* TTL_Tau1GenMatchMother0Status;
	std::vector<int>* TTL_Tau1GenMatchMother1Status;
	std::vector<int>* TTL_Tau1GenMatchGrandmother00Status;
	std::vector<int>* TTL_Tau1GenMatchGrandmother01Status;
	std::vector<int>* TTL_Tau1GenMatchGrandmother10Status;
	std::vector<int>* TTL_Tau1GenMatchGrandmother11Status;
	std::vector<int>* TTL_Tau2MomentumRank;
	std::vector<float>* TTL_Tau2Pt;
	std::vector<float>* TTL_Tau2Eta;
	std::vector<float>* TTL_Tau2Phi;
	std::vector<unsigned int>* TTL_Tau2NProngs;
	std::vector<unsigned int>* TTL_Tau2NSignalGammas;
	std::vector<unsigned int>* TTL_Tau2NSignalNeutrals;
	std::vector<unsigned int>* TTL_Tau2DecayMode;
	std::vector<float>* TTL_Tau2EmFraction;
	std::vector<bool>* TTL_Tau2IsInTheCracks;
	std::vector<bool>* TTL_Tau2HPSagainstElectronDeadECAL;
	std::vector<bool>* TTL_Tau2HPSagainstElectronLoose;
	std::vector<bool>* TTL_Tau2HPSagainstElectronLooseMVA2;
	std::vector<bool>* TTL_Tau2HPSagainstElectronLooseMVA3;
	std::vector<bool>* TTL_Tau2HPSagainstElectronMVA;
	std::vector<bool>* TTL_Tau2HPSagainstElectronMVA2category;
	std::vector<float>* TTL_Tau2HPSagainstElectronMVA2raw;
	std::vector<bool>* TTL_Tau2HPSagainstElectronMVA3category;
	std::vector<float>* TTL_Tau2HPSagainstElectronMVA3raw;
	std::vector<bool>* TTL_Tau2HPSagainstElectronMedium;
	std::vector<bool>* TTL_Tau2HPSagainstElectronMediumMVA2;
	std::vector<bool>* TTL_Tau2HPSagainstElectronMediumMVA3;
	std::vector<bool>* TTL_Tau2HPSagainstElectronTight;
	std::vector<bool>* TTL_Tau2HPSagainstElectronTightMVA2;
	std::vector<bool>* TTL_Tau2HPSagainstElectronTightMVA3;
	std::vector<bool>* TTL_Tau2HPSagainstElectronVLooseMVA2;
	std::vector<bool>* TTL_Tau2HPSagainstElectronVTightMVA3;
	std::vector<bool>* TTL_Tau2HPSagainstMuonLoose;
	std::vector<bool>* TTL_Tau2HPSagainstMuonLoose2;
	std::vector<bool>* TTL_Tau2HPSagainstMuonMedium;
	std::vector<bool>* TTL_Tau2HPSagainstMuonMedium2;
	std::vector<bool>* TTL_Tau2HPSagainstMuonTight;
	std::vector<bool>* TTL_Tau2HPSagainstMuonTight2;
	std::vector<float>* TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw;
	std::vector<float>* TTL_Tau2HPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
	std::vector<float>* TTL_Tau2HPSbyIsolationMVA2raw;
	std::vector<bool>* TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TTL_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TTL_Tau2HPSbyLooseIsolationMVA;
	std::vector<bool>* TTL_Tau2HPSbyLooseIsolationMVA2;
	std::vector<bool>* TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TTL_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TTL_Tau2HPSbyMediumIsolationMVA;
	std::vector<bool>* TTL_Tau2HPSbyMediumIsolationMVA2;
	std::vector<bool>* TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TTL_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TTL_Tau2HPSbyTightIsolationMVA;
	std::vector<bool>* TTL_Tau2HPSbyTightIsolationMVA2;
	std::vector<bool>* TTL_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TTL_Tau2HPSdecayModeFinding;
	std::vector<float>* TTL_Tau2HPSbyIsolationMVAraw;
	std::vector<float>* TTL_Tau2LTPt;
	std::vector<float>* TTL_Tau2Charge;
	std::vector<bool>* TTL_Tau2LTvalid;
	std::vector<float>* TTL_Tau2LTIpVtdxy;
	std::vector<float>* TTL_Tau2LTIpVtdz;
	std::vector<float>* TTL_Tau2LTIpVtdxyError;
	std::vector<float>* TTL_Tau2LTIpVtdzError;
	std::vector<float>* TTL_Tau2LTvx;
	std::vector<float>* TTL_Tau2LTvy;
	std::vector<float>* TTL_Tau2LTvz;
	std::vector<unsigned int>* TTL_Tau2LTValidHits;
	std::vector<float>* TTL_Tau2LTNormChiSqrd;
	std::vector<int>* TTL_Tau2GenMatchDaughter0Id;
	std::vector<int>* TTL_Tau2GenMatchDaughter1Id;
	std::vector<int>* TTL_Tau2GenMatchId;
	std::vector<int>* TTL_Tau2GenMatchMother0Id;
	std::vector<int>* TTL_Tau2GenMatchMother1Id;
	std::vector<int>* TTL_Tau2GenMatchGrandmother00Id;
	std::vector<int>* TTL_Tau2GenMatchGrandmother01Id;
	std::vector<int>* TTL_Tau2GenMatchGrandmother10Id;
	std::vector<int>* TTL_Tau2GenMatchGrandmother11Id;
	std::vector<int>* TTL_Tau2GenMatchDaughter0Status;
	std::vector<int>* TTL_Tau2GenMatchDaughter1Status;
	std::vector<int>* TTL_Tau2GenMatchStatus;
	std::vector<int>* TTL_Tau2GenMatchMother0Status;
	std::vector<int>* TTL_Tau2GenMatchMother1Status;
	std::vector<int>* TTL_Tau2GenMatchGrandmother00Status;
	std::vector<int>* TTL_Tau2GenMatchGrandmother01Status;
	std::vector<int>* TTL_Tau2GenMatchGrandmother10Status;
	std::vector<int>* TTL_Tau2GenMatchGrandmother11Status;
	std::vector<int>* TTL_MuonMomentumRank;
	std::vector<int>* TTL_ElectronMomentumRank;
	std::vector<int>* TTL_LeptonMomentumRank;
	std::vector<float>* TTL_LeptonIsMuon;
	std::vector<float>* TTL_LeptonIsElectron;
	std::vector<float>* TTL_LeptonPt;
	std::vector<float>* TTL_LeptonEta;
	std::vector<float>* TTL_LeptonPhi;
	std::vector<float>* TTL_LeptonRelIso;
	std::vector<bool>* TTL_LeptonIsLoose;
	std::vector<bool>* TTL_LeptonIsTight;
	std::vector<unsigned int>* TTL_NumLooseMuons;
	std::vector<unsigned int>* TTL_NumExLooseMuons;
	std::vector<unsigned int>* TTL_NumTightMuons;
	std::vector<unsigned int>* TTL_NumLooseElectrons;
	std::vector<unsigned int>* TTL_NumExLooseElectrons;
	std::vector<unsigned int>* TTL_NumTightElectrons;
	std::vector<int>* TTL_LeptonGenMatchDaughter0Id;
	std::vector<int>* TTL_LeptonGenMatchDaughter1Id;
	std::vector<int>* TTL_LeptonGenMatchId;
	std::vector<int>* TTL_LeptonGenMatchMother0Id;
	std::vector<int>* TTL_LeptonGenMatchMother1Id;
	std::vector<int>* TTL_LeptonGenMatchGrandmother00Id;
	std::vector<int>* TTL_LeptonGenMatchGrandmother01Id;
	std::vector<int>* TTL_LeptonGenMatchGrandmother10Id;
	std::vector<int>* TTL_LeptonGenMatchGrandmother11Id;
	std::vector<int>* TTL_LeptonGenMatchDaughter0Status;
	std::vector<int>* TTL_LeptonGenMatchDaughter1Status;
	std::vector<int>* TTL_LeptonGenMatchStatus;
	std::vector<int>* TTL_LeptonGenMatchMother0Status;
	std::vector<int>* TTL_LeptonGenMatchMother1Status;
	std::vector<int>* TTL_LeptonGenMatchGrandmother00Status;
	std::vector<int>* TTL_LeptonGenMatchGrandmother01Status;
	std::vector<int>* TTL_LeptonGenMatchGrandmother10Status;
	std::vector<int>* TTL_LeptonGenMatchGrandmother11Status;
	std::vector<float>* TTL_DitauVisibleMass;
	std::vector<float>* TTL_DitauMETMass;
	std::vector<float>* TTL_DitauCosDeltaPhi;
	std::vector<float>* TTL_DitauDeltaR;
	std::vector<float>* TTL_Tau1LeptonDeltaR;
	std::vector<float>* TTL_Tau2LeptonDeltaR;
	std::vector<float>* TTL_HT;
	std::vector<unsigned int>* TTL_NumCSVLbtagJets;
	std::vector<unsigned int>* TTL_NumCSVMbtagJets;
	std::vector<unsigned int>* TTL_NumCSVTbtagJets;
	std::vector<unsigned int>* TTL_NumNonCSVLbtagJets;
	std::vector<unsigned int>* TTL_NumNonCSVMbtagJets;
	std::vector<unsigned int>* TTL_NumNonCSVTbtagJets;
	std::vector<unsigned int>* TTL_NumCleanCSVLbtagJets;
	std::vector<unsigned int>* TTL_NumCleanCSVMbtagJets;
	std::vector<unsigned int>* TTL_NumCleanCSVTbtagJets;
	std::vector<unsigned int>* TTL_NumCleanNonCSVLbtagJets;
	std::vector<unsigned int>* TTL_NumCleanNonCSVMbtagJets;
	std::vector<unsigned int>* TTL_NumCleanNonCSVTbtagJets;
	std::vector<float>* TTL_LeptonEventWeight;
	std::vector<float>* TTL_CSVeventWeight;
	std::vector<float>* TTL_CSVeventWeightHFdown;
	std::vector<float>* TTL_CSVeventWeightHFup;
	std::vector<float>* TTL_CSVeventWeightLFdown;
	std::vector<float>* TTL_CSVeventWeightLFup;
	std::vector<float>* TTL_CSVeventWeightHFStats1down;
	std::vector<float>* TTL_CSVeventWeightHFStats1up;
	std::vector<float>* TTL_CSVeventWeightLFStats1down;
	std::vector<float>* TTL_CSVeventWeightLFStats1up;
	std::vector<float>* TTL_CSVeventWeightHFStats2down;
	std::vector<float>* TTL_CSVeventWeightHFStats2up;
	std::vector<float>* TTL_CSVeventWeightLFStats2down;
	std::vector<float>* TTL_CSVeventWeightLFStats2up;
	unsigned int TLL_NumTaus;
	std::vector<unsigned int>* TLL_NumLooseMuons;
	std::vector<unsigned int>* TLL_NumExLooseMuons;
	std::vector<unsigned int>* TLL_NumTightMuons;
	std::vector<unsigned int>* TLL_NumLooseElectrons;
	std::vector<unsigned int>* TLL_NumExLooseElectrons;
	std::vector<unsigned int>* TLL_NumTightElectrons;
	unsigned int TLL_NumCombos;
	std::vector<int>* TLL_MomentumRank;
	std::vector<int>* TLL_TauMomentumRank;
	std::vector<float>* TLL_TauPt;
	std::vector<float>* TLL_TauEta;
	std::vector<float>* TLL_TauPhi;
	std::vector<unsigned int>* TLL_TauNProngs;
	std::vector<unsigned int>* TLL_TauNSignalGammas;
	std::vector<unsigned int>* TLL_TauNSignalNeutrals;
	std::vector<unsigned int>* TLL_TauDecayMode;
	std::vector<float>* TLL_TauEmFraction;
	std::vector<bool>* TLL_TauIsInTheCracks;
	std::vector<bool>* TLL_TauHPSagainstElectronDeadECAL;
	std::vector<bool>* TLL_TauHPSagainstElectronLoose;
	std::vector<bool>* TLL_TauHPSagainstElectronLooseMVA2;
	std::vector<bool>* TLL_TauHPSagainstElectronLooseMVA3;
	std::vector<bool>* TLL_TauHPSagainstElectronMVA;
	std::vector<bool>* TLL_TauHPSagainstElectronMVA2category;
	std::vector<float>* TLL_TauHPSagainstElectronMVA2raw;
	std::vector<bool>* TLL_TauHPSagainstElectronMVA3category;
	std::vector<float>* TLL_TauHPSagainstElectronMVA3raw;
	std::vector<bool>* TLL_TauHPSagainstElectronMedium;
	std::vector<bool>* TLL_TauHPSagainstElectronMediumMVA2;
	std::vector<bool>* TLL_TauHPSagainstElectronMediumMVA3;
	std::vector<bool>* TLL_TauHPSagainstElectronTight;
	std::vector<bool>* TLL_TauHPSagainstElectronTightMVA2;
	std::vector<bool>* TLL_TauHPSagainstElectronTightMVA3;
	std::vector<bool>* TLL_TauHPSagainstElectronVLooseMVA2;
	std::vector<bool>* TLL_TauHPSagainstElectronVTightMVA3;
	std::vector<bool>* TLL_TauHPSagainstMuonLoose;
	std::vector<bool>* TLL_TauHPSagainstMuonLoose2;
	std::vector<bool>* TLL_TauHPSagainstMuonMedium;
	std::vector<bool>* TLL_TauHPSagainstMuonMedium2;
	std::vector<bool>* TLL_TauHPSagainstMuonTight;
	std::vector<bool>* TLL_TauHPSagainstMuonTight2;
	std::vector<float>* TLL_TauHPSbyCombinedIsolationDeltaBetaCorrRaw;
	std::vector<float>* TLL_TauHPSbyCombinedIsolationDeltaBetaCorrRaw3Hits;
	std::vector<float>* TLL_TauHPSbyIsolationMVA2raw;
	std::vector<bool>* TLL_TauHPSbyLooseCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TLL_TauHPSbyLooseCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TLL_TauHPSbyLooseIsolationMVA;
	std::vector<bool>* TLL_TauHPSbyLooseIsolationMVA2;
	std::vector<bool>* TLL_TauHPSbyMediumCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TLL_TauHPSbyMediumCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TLL_TauHPSbyMediumIsolationMVA;
	std::vector<bool>* TLL_TauHPSbyMediumIsolationMVA2;
	std::vector<bool>* TLL_TauHPSbyTightCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TLL_TauHPSbyTightCombinedIsolationDeltaBetaCorr3Hits;
	std::vector<bool>* TLL_TauHPSbyTightIsolationMVA;
	std::vector<bool>* TLL_TauHPSbyTightIsolationMVA2;
	std::vector<bool>* TLL_TauHPSbyVLooseCombinedIsolationDeltaBetaCorr;
	std::vector<bool>* TLL_TauHPSdecayModeFinding;
	std::vector<float>* TLL_TauHPSbyIsolationMVAraw;
	std::vector<float>* TLL_TauLTPt;
	std::vector<float>* TLL_TauCharge;
	std::vector<bool>* TLL_TauLTvalid;
	std::vector<float>* TLL_TauLTIpVtdxy;
	std::vector<float>* TLL_TauLTIpVtdz;
	std::vector<float>* TLL_TauLTIpVtdxyError;
	std::vector<float>* TLL_TauLTIpVtdzError;
	std::vector<float>* TLL_TauLTvx;
	std::vector<float>* TLL_TauLTvy;
	std::vector<float>* TLL_TauLTvz;
	std::vector<unsigned int>* TLL_TauLTValidHits;
	std::vector<float>* TLL_TauLTNormChiSqrd;
	std::vector<int>* TLL_TauGenMatchDaughter0Id;
	std::vector<int>* TLL_TauGenMatchDaughter1Id;
	std::vector<int>* TLL_TauGenMatchId;
	std::vector<int>* TLL_TauGenMatchMother0Id;
	std::vector<int>* TLL_TauGenMatchMother1Id;
	std::vector<int>* TLL_TauGenMatchGrandmother00Id;
	std::vector<int>* TLL_TauGenMatchGrandmother01Id;
	std::vector<int>* TLL_TauGenMatchGrandmother10Id;
	std::vector<int>* TLL_TauGenMatchGrandmother11Id;
	std::vector<int>* TLL_TauGenMatchDaughter0Status;
	std::vector<int>* TLL_TauGenMatchDaughter1Status;
	std::vector<int>* TLL_TauGenMatchStatus;
	std::vector<int>* TLL_TauGenMatchMother0Status;
	std::vector<int>* TLL_TauGenMatchMother1Status;
	std::vector<int>* TLL_TauGenMatchGrandmother00Status;
	std::vector<int>* TLL_TauGenMatchGrandmother01Status;
	std::vector<int>* TLL_TauGenMatchGrandmother10Status;
	std::vector<int>* TLL_TauGenMatchGrandmother11Status;
	std::vector<float>* TLL_Lepton1IsMuon;
	std::vector<float>* TLL_Lepton1IsElectron;
	std::vector<float>* TLL_Lepton1Pt;
	std::vector<float>* TLL_Lepton1Eta;
	std::vector<float>* TLL_Lepton1Phi;
	std::vector<float>* TLL_Lepton1RelIso;
	std::vector<bool>* TLL_Lepton1IsLoose;
	std::vector<bool>* TLL_Lepton1IsTight;
	std::vector<float>* TLL_Lepton1EventWeight;
	std::vector<int>* TLL_Lepton1GenMatchDaughter0Id;
	std::vector<int>* TLL_Lepton1GenMatchDaughter1Id;
	std::vector<int>* TLL_Lepton1GenMatchId;
	std::vector<int>* TLL_Lepton1GenMatchMother0Id;
	std::vector<int>* TLL_Lepton1GenMatchMother1Id;
	std::vector<int>* TLL_Lepton1GenMatchGrandmother00Id;
	std::vector<int>* TLL_Lepton1GenMatchGrandmother01Id;
	std::vector<int>* TLL_Lepton1GenMatchGrandmother10Id;
	std::vector<int>* TLL_Lepton1GenMatchGrandmother11Id;
	std::vector<int>* TLL_Lepton1GenMatchDaughter0Status;
	std::vector<int>* TLL_Lepton1GenMatchDaughter1Status;
	std::vector<int>* TLL_Lepton1GenMatchStatus;
	std::vector<int>* TLL_Lepton1GenMatchMother0Status;
	std::vector<int>* TLL_Lepton1GenMatchMother1Status;
	std::vector<int>* TLL_Lepton1GenMatchGrandmother00Status;
	std::vector<int>* TLL_Lepton1GenMatchGrandmother01Status;
	std::vector<int>* TLL_Lepton1GenMatchGrandmother10Status;
	std::vector<int>* TLL_Lepton1GenMatchGrandmother11Status;
	std::vector<float>* TLL_Lepton2IsMuon;
	std::vector<float>* TLL_Lepton2IsElectron;
	std::vector<float>* TLL_Lepton2Pt;
	std::vector<float>* TLL_Lepton2Eta;
	std::vector<float>* TLL_Lepton2Phi;
	std::vector<float>* TLL_Lepton2RelIso;
	std::vector<bool>* TLL_Lepton2IsLoose;
	std::vector<bool>* TLL_Lepton2IsTight;
	std::vector<float>* TLL_Lepton2EventWeight;
	std::vector<int>* TLL_Lepton2GenMatchDaughter0Id;
	std::vector<int>* TLL_Lepton2GenMatchDaughter1Id;
	std::vector<int>* TLL_Lepton2GenMatchId;
	std::vector<int>* TLL_Lepton2GenMatchMother0Id;
	std::vector<int>* TLL_Lepton2GenMatchMother1Id;
	std::vector<int>* TLL_Lepton2GenMatchGrandmother00Id;
	std::vector<int>* TLL_Lepton2GenMatchGrandmother01Id;
	std::vector<int>* TLL_Lepton2GenMatchGrandmother10Id;
	std::vector<int>* TLL_Lepton2GenMatchGrandmother11Id;
	std::vector<int>* TLL_Lepton2GenMatchDaughter0Status;
	std::vector<int>* TLL_Lepton2GenMatchDaughter1Status;
	std::vector<int>* TLL_Lepton2GenMatchStatus;
	std::vector<int>* TLL_Lepton2GenMatchMother0Status;
	std::vector<int>* TLL_Lepton2GenMatchMother1Status;
	std::vector<int>* TLL_Lepton2GenMatchGrandmother00Status;
	std::vector<int>* TLL_Lepton2GenMatchGrandmother01Status;
	std::vector<int>* TLL_Lepton2GenMatchGrandmother10Status;
	std::vector<int>* TLL_Lepton2GenMatchGrandmother11Status;
	std::vector<float>* TLL_TauLepton1VisibleMass;
	std::vector<float>* TLL_TauLepton2VisibleMass;
	std::vector<float>* TLL_TauLepton1METMass;
	std::vector<float>* TLL_TauLepton2METMass;
	std::vector<float>* TLL_Lepton1Lepton2VisibleMass;
	std::vector<float>* TLL_TauLepton1CosDeltaPhi;
	std::vector<float>* TLL_TauLepton2CosDeltaPhi;
	std::vector<float>* TLL_Lepton1Lepton2CosDeltaPhi;
	std::vector<float>* TLL_TauLepton1DeltaR;
	std::vector<float>* TLL_TauLepton2DeltaR;
	std::vector<float>* TLL_Lepton1Lepton2DeltaR;
	std::vector<float>* TLL_HT;
	std::vector<unsigned int>* TLL_NumCSVLbtagJets;
	std::vector<unsigned int>* TLL_NumCSVMbtagJets;
	std::vector<unsigned int>* TLL_NumCSVTbtagJets;
	std::vector<unsigned int>* TLL_NumNonCSVLbtagJets;
	std::vector<unsigned int>* TLL_NumNonCSVMbtagJets;
	std::vector<unsigned int>* TLL_NumNonCSVTbtagJets;
	std::vector<unsigned int>* TLL_NumCleanCSVLbtagJets;
	std::vector<unsigned int>* TLL_NumCleanCSVMbtagJets;
	std::vector<unsigned int>* TLL_NumCleanCSVTbtagJets;
	std::vector<unsigned int>* TLL_NumCleanNonCSVLbtagJets;
	std::vector<unsigned int>* TLL_NumCleanNonCSVMbtagJets;
	std::vector<unsigned int>* TLL_NumCleanNonCSVTbtagJets;
