	Ev_runNumber = 0;
	Ev_eventNumber = 0;
	Ev_lumiBlock = 0;
	Ev_numInteractionsBXm1 = 0;
	Ev_numInteractionsBX0 = 0;
	Ev_numInteractionsBXp1 = 0;
	Ev_MET = 0;
	Ev_METphi = 0;
	GT_NumGenTaus = 0;
	GT_MomentumRank->clear();
	GT_Pt->clear();
	GT_Eta->clear();
	GT_Phi->clear();
	GT_VisPt->clear();
	GT_VisEta->clear();
	GT_VisPhi->clear();
	GT_ParentId->clear();
	GT_ToElectron->clear();
	GT_ToMuon->clear();
	GT_ToHadrons->clear();
	T_NumTaus = 0;
	T_MomentumRank->clear();
	T_Pt->clear();
	T_Eta->clear();
	T_Phi->clear();
	E_NumElectrons = 0;
	E_MomentumRank->clear();
	E_Pt->clear();
	E_Eta->clear();
	E_Phi->clear();
	M_NumMuons = 0;
	M_MomentumRank->clear();
	M_Pt->clear();
	M_Eta->clear();
	M_Phi->clear();
	J_NumJets = 0;
	J_MomentumRank->clear();
	J_Pt->clear();
	J_Eta->clear();
	J_Phi->clear();
	J_combSecVtxBTag->clear();
	J_combSecVtxLooseBTag->clear();
	J_combSecVtxMediumBTag->clear();
	J_combSecVtxTightBTag->clear();
	TT_NumCombos = 0;
	TT_MomentumRank->clear();
	TTM_NumTaus = 0;
	TTM_NumMuons = 0;
	TTM_NumCombos = 0;
	TTM_MomentumRank->clear();
	TTM_Tau1MomentumRank->clear();
	TTM_Tau1Pt->clear();
	TTM_Tau1Eta->clear();
	TTM_Tau1Phi->clear();
	TTM_Tau1NProngs->clear();
	TTM_Tau1NSignalGammas->clear();
	TTM_Tau1NSignalNeutrals->clear();
	TTM_Tau1NSignalPiZeros->clear();
	TTM_Tau1DecayMode->clear();
	TTM_Tau1EmFraction->clear();
	TTM_Tau1IsInTheCracks->clear();
	TTM_Tau1HPSagainstElectronLoose->clear();
	TTM_Tau1HPSagainstElectronMVA->clear();
	TTM_Tau1HPSagainstElectronMedium->clear();
	TTM_Tau1HPSagainstElectronTight->clear();
	TTM_Tau1HPSagainstMuonLoose->clear();
	TTM_Tau1HPSagainstMuonMedium->clear();
	TTM_Tau1HPSagainstMuonTight->clear();
	TTM_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
	TTM_Tau1HPSbyLooseIsolation->clear();
	TTM_Tau1HPSbyLooseIsolationDeltaBetaCorr->clear();
	TTM_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
	TTM_Tau1HPSbyMediumIsolation->clear();
	TTM_Tau1HPSbyMediumIsolationDeltaBetaCorr->clear();
	TTM_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
	TTM_Tau1HPSbyTightIsolation->clear();
	TTM_Tau1HPSbyTightIsolationDeltaBetaCorr->clear();
	TTM_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
	TTM_Tau1HPSbyVLooseIsolation->clear();
	TTM_Tau1HPSbyVLooseIsolationDeltaBetaCorr->clear();
	TTM_Tau1HPSdecayModeFinding->clear();
	TTM_Tau1LTPt->clear();
	TTM_Tau1Charge->clear();
	TTM_Tau1LTvalid->clear();
	TTM_Tau1LTIpVtdxy->clear();
	TTM_Tau1LTIpVtdz->clear();
	TTM_Tau1LTIpVtdxyError->clear();
	TTM_Tau1LTIpVtdzError->clear();
	TTM_Tau1LTvx->clear();
	TTM_Tau1LTvy->clear();
	TTM_Tau1LTvz->clear();
	TTM_Tau1LTValidHits->clear();
	TTM_Tau1LTNormChiSqrd->clear();
	TTM_Tau2MomentumRank->clear();
	TTM_Tau2Pt->clear();
	TTM_Tau2Eta->clear();
	TTM_Tau2Phi->clear();
	TTM_Tau2NProngs->clear();
	TTM_Tau2NSignalGammas->clear();
	TTM_Tau2NSignalNeutrals->clear();
	TTM_Tau2NSignalPiZeros->clear();
	TTM_Tau2DecayMode->clear();
	TTM_Tau2EmFraction->clear();
	TTM_Tau2IsInTheCracks->clear();
	TTM_Tau2HPSagainstElectronLoose->clear();
	TTM_Tau2HPSagainstElectronMVA->clear();
	TTM_Tau2HPSagainstElectronMedium->clear();
	TTM_Tau2HPSagainstElectronTight->clear();
	TTM_Tau2HPSagainstMuonLoose->clear();
	TTM_Tau2HPSagainstMuonMedium->clear();
	TTM_Tau2HPSagainstMuonTight->clear();
	TTM_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
	TTM_Tau2HPSbyLooseIsolation->clear();
	TTM_Tau2HPSbyLooseIsolationDeltaBetaCorr->clear();
	TTM_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
	TTM_Tau2HPSbyMediumIsolation->clear();
	TTM_Tau2HPSbyMediumIsolationDeltaBetaCorr->clear();
	TTM_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
	TTM_Tau2HPSbyTightIsolation->clear();
	TTM_Tau2HPSbyTightIsolationDeltaBetaCorr->clear();
	TTM_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
	TTM_Tau2HPSbyVLooseIsolation->clear();
	TTM_Tau2HPSbyVLooseIsolationDeltaBetaCorr->clear();
	TTM_Tau2HPSdecayModeFinding->clear();
	TTM_Tau2LTPt->clear();
	TTM_Tau2Charge->clear();
	TTM_Tau2LTvalid->clear();
	TTM_Tau2LTIpVtdxy->clear();
	TTM_Tau2LTIpVtdz->clear();
	TTM_Tau2LTIpVtdxyError->clear();
	TTM_Tau2LTIpVtdzError->clear();
	TTM_Tau2LTvx->clear();
	TTM_Tau2LTvy->clear();
	TTM_Tau2LTvz->clear();
	TTM_Tau2LTValidHits->clear();
	TTM_Tau2LTNormChiSqrd->clear();
	TTM_MuonPt->clear();
	TTM_MuonEta->clear();
	TTM_MuonPhi->clear();
	TTM_DitauVisibleMass->clear();
	TTM_DitauMETMass->clear();
	TTM_DitauCosDeltaPhi->clear();
	TTM_HT->clear();
	TTM_NumCSVLbtags->clear();
	TTM_NumCSVMbtags->clear();
	TTM_NumCSVTbtags->clear();
	TTM_NumCSVLextraJets->clear();
	TTM_NumCSVMextraJets->clear();
	TTM_NumCSVTextraJets->clear();
	TTE_NumCombos = 0;
	TTE_MomentumRank->clear();
