	double Ev_runNumber;
	double Ev_eventNumber;
	double Ev_lumiBlock;
	int Ev_numInteractionsBXm1;
	int Ev_numInteractionsBX0;
	int Ev_numInteractionsBXp1;
	double Ev_MET;
	double Ev_METphi;
	int GT_NumGenTaus;
	vector<float>* GT_MomentumRank;
	vector<float>* GT_Pt;
	vector<float>* GT_Eta;
	vector<float>* GT_Phi;
	vector<float>* GT_VisPt;
	vector<float>* GT_VisEta;
	vector<float>* GT_VisPhi;
	vector<int>* GT_ParentId;
	vector<bool>* GT_ToElectron;
	vector<bool>* GT_ToMuon;
	vector<bool>* GT_ToHadrons;
	int T_NumTaus;
	vector<float>* T_MomentumRank;
	vector<float>* T_Pt;
	vector<float>* T_Eta;
	vector<float>* T_Phi;
	int E_NumElectrons;
	vector<float>* E_MomentumRank;
	vector<float>* E_Pt;
	vector<float>* E_Eta;
	vector<float>* E_Phi;
	int M_NumMuons;
	vector<float>* M_MomentumRank;
	vector<float>* M_Pt;
	vector<float>* M_Eta;
	vector<float>* M_Phi;
	int J_NumJets;
	vector<float>* J_MomentumRank;
	vector<float>* J_Pt;
	vector<float>* J_Eta;
	vector<float>* J_Phi;
	vector<float>* J_combSecVtxBTag;
	vector<bool>* J_combSecVtxLooseBTag;
	vector<bool>* J_combSecVtxMediumBTag;
	vector<bool>* J_combSecVtxTightBTag;
	int TT_NumCombos;
	vector<float>* TT_MomentumRank;
	unsigned int TTM_NumTaus;
	unsigned int TTM_NumMuons;
	unsigned int TTM_NumCombos;
	vector<unsigned int>* TTM_MomentumRank;
	vector<unsigned int>* TTM_Tau1MomentumRank;
	vector<float>* TTM_Tau1Pt;
	vector<float>* TTM_Tau1Eta;
	vector<float>* TTM_Tau1Phi;
	vector<unsigned int>* TTM_Tau1NProngs;
	vector<unsigned int>* TTM_Tau1NSignalGammas;
	vector<unsigned int>* TTM_Tau1NSignalNeutrals;
	vector<unsigned int>* TTM_Tau1NSignalPiZeros;
	vector<unsigned int>* TTM_Tau1DecayMode;
	vector<float>* TTM_Tau1EmFraction;
	vector<bool>* TTM_Tau1IsInTheCracks;
	vector<bool>* TTM_Tau1HPSagainstElectronLoose;
	vector<bool>* TTM_Tau1HPSagainstElectronMVA;
	vector<bool>* TTM_Tau1HPSagainstElectronMedium;
	vector<bool>* TTM_Tau1HPSagainstElectronTight;
	vector<bool>* TTM_Tau1HPSagainstMuonLoose;
	vector<bool>* TTM_Tau1HPSagainstMuonMedium;
	vector<bool>* TTM_Tau1HPSagainstMuonTight;
	vector<bool>* TTM_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau1HPSbyLooseIsolation;
	vector<bool>* TTM_Tau1HPSbyLooseIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau1HPSbyMediumIsolation;
	vector<bool>* TTM_Tau1HPSbyMediumIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau1HPSbyTightIsolation;
	vector<bool>* TTM_Tau1HPSbyTightIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau1HPSbyVLooseIsolation;
	vector<bool>* TTM_Tau1HPSbyVLooseIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau1HPSdecayModeFinding;
	vector<float>* TTM_Tau1LTPt;
	vector<float>* TTM_Tau1Charge;
	vector<bool>* TTM_Tau1LTvalid;
	vector<float>* TTM_Tau1LTIpVtdxy;
	vector<float>* TTM_Tau1LTIpVtdz;
	vector<float>* TTM_Tau1LTIpVtdxyError;
	vector<float>* TTM_Tau1LTIpVtdzError;
	vector<float>* TTM_Tau1LTvx;
	vector<float>* TTM_Tau1LTvy;
	vector<float>* TTM_Tau1LTvz;
	vector<unsigned int>* TTM_Tau1LTValidHits;
	vector<float>* TTM_Tau1LTNormChiSqrd;
	vector<unsigned int>* TTM_Tau2MomentumRank;
	vector<float>* TTM_Tau2Pt;
	vector<float>* TTM_Tau2Eta;
	vector<float>* TTM_Tau2Phi;
	vector<unsigned int>* TTM_Tau2NProngs;
	vector<unsigned int>* TTM_Tau2NSignalGammas;
	vector<unsigned int>* TTM_Tau2NSignalNeutrals;
	vector<unsigned int>* TTM_Tau2NSignalPiZeros;
	vector<unsigned int>* TTM_Tau2DecayMode;
	vector<float>* TTM_Tau2EmFraction;
	vector<bool>* TTM_Tau2IsInTheCracks;
	vector<bool>* TTM_Tau2HPSagainstElectronLoose;
	vector<bool>* TTM_Tau2HPSagainstElectronMVA;
	vector<bool>* TTM_Tau2HPSagainstElectronMedium;
	vector<bool>* TTM_Tau2HPSagainstElectronTight;
	vector<bool>* TTM_Tau2HPSagainstMuonLoose;
	vector<bool>* TTM_Tau2HPSagainstMuonMedium;
	vector<bool>* TTM_Tau2HPSagainstMuonTight;
	vector<bool>* TTM_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau2HPSbyLooseIsolation;
	vector<bool>* TTM_Tau2HPSbyLooseIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau2HPSbyMediumIsolation;
	vector<bool>* TTM_Tau2HPSbyMediumIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau2HPSbyTightIsolation;
	vector<bool>* TTM_Tau2HPSbyTightIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau2HPSbyVLooseIsolation;
	vector<bool>* TTM_Tau2HPSbyVLooseIsolationDeltaBetaCorr;
	vector<bool>* TTM_Tau2HPSdecayModeFinding;
	vector<float>* TTM_Tau2LTPt;
	vector<float>* TTM_Tau2Charge;
	vector<bool>* TTM_Tau2LTvalid;
	vector<float>* TTM_Tau2LTIpVtdxy;
	vector<float>* TTM_Tau2LTIpVtdz;
	vector<float>* TTM_Tau2LTIpVtdxyError;
	vector<float>* TTM_Tau2LTIpVtdzError;
	vector<float>* TTM_Tau2LTvx;
	vector<float>* TTM_Tau2LTvy;
	vector<float>* TTM_Tau2LTvz;
	vector<unsigned int>* TTM_Tau2LTValidHits;
	vector<float>* TTM_Tau2LTNormChiSqrd;
	vector<float>* TTM_MuonPt;
	vector<float>* TTM_MuonEta;
	vector<float>* TTM_MuonPhi;
	vector<float>* TTM_DitauVisibleMass;
	vector<float>* TTM_DitauMETMass;
	vector<float>* TTM_DitauCosDeltaPhi;
	vector<float>* TTM_HT;
	vector<unsigned int>* TTM_NumCSVLbtags;
	vector<unsigned int>* TTM_NumCSVMbtags;
	vector<unsigned int>* TTM_NumCSVTbtags;
	vector<unsigned int>* TTM_NumCSVLextraJets;
	vector<unsigned int>* TTM_NumCSVMextraJets;
	vector<unsigned int>* TTM_NumCSVTextraJets;
	int TTE_NumCombos;
	vector<float>* TTE_MomentumRank;
