#!/usr/bin/env python

import glob
import os
import re
import sys

if len(sys.argv) != 2:
    sys.stderr.write("usage: {p} basedir\n".format(p=os.path.basename(sys.argv[0])))
    sys.exit(1)

basedir = sys.argv[1]
sys_re = re.compile(re.escape(basedir) + '_(.*(?:[Uu]p|[Dd]own))')

for d in glob.glob(basedir + '_*'):
    m = sys_re.match(d)
    if not m:
        continue
    unc = m.group(1)
    print "{u} = [\n    fullFilePath = {p}/nidra_ditau.root\n]".format(u=unc, p=d)
