	Ev_runNumber = 0;
	Ev_eventNumber = 0;
	Ev_lumiBlock = 0;
	Ev_numInteractionsBXm1 = 0;
	Ev_numInteractionsBX0 = 0;
	Ev_numInteractionsBXp1 = 0;
	Ev_numPrimaryVertices = 0;
	Ev_puWeight = 0;
	Ev_MET = 0;
	Ev_METphi = 0;
	GT_NumGenTaus = 0;
	GT_MomentumRank->clear();
	GT_Pt->clear();
	GT_Eta->clear();
	GT_Phi->clear();
	GT_VisPt->clear();
	GT_VisEta->clear();
	GT_VisPhi->clear();
	GT_ToElectron->clear();
	GT_ToMuon->clear();
	GT_ToHadrons->clear();
	GT_ParentId->clear();
	GT_ParentP->clear();
	GT_ParentPt->clear();
	GT_ParentEta->clear();
	GT_ParentPhi->clear();
	GJ_NumGenJets = 0;
	GJ_MomentumRank->clear();
	GJ_Pt->clear();
	GJ_Eta->clear();
	GJ_Phi->clear();
	GJ_IsBjet->clear();
	T_NumTaus = 0;
	T_MomentumRank->clear();
	T_Pt->clear();
	T_Eta->clear();
	T_Phi->clear();
	T_NProngs->clear();
	T_NSignalGammas->clear();
	T_NSignalNeutrals->clear();
	T_DecayMode->clear();
	T_EmFraction->clear();
	T_IsInTheCracks->clear();
	T_HPSagainstElectronLoose->clear();
	T_HPSagainstElectronMVA->clear();
	T_HPSagainstElectronMedium->clear();
	T_HPSagainstElectronTight->clear();
	T_HPSagainstMuonLoose->clear();
	T_HPSagainstMuonMedium->clear();
	T_HPSagainstMuonTight->clear();
	T_HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
	T_HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
	T_HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
	T_HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
	T_HPSdecayModeFinding->clear();
	T_LTPt->clear();
	T_Charge->clear();
	T_LTvalid->clear();
	T_LTIpVtdxy->clear();
	T_LTIpVtdz->clear();
	T_LTIpVtdxyError->clear();
	T_LTIpVtdzError->clear();
	T_LTvx->clear();
	T_LTvy->clear();
	T_LTvz->clear();
	T_LTValidHits->clear();
	T_LTNormChiSqrd->clear();
	E_NumElectrons = 0;
	E_MomentumRank->clear();
	E_Pt->clear();
	E_Eta->clear();
	E_Phi->clear();
	E_IsTightElectron->clear();
	E_IsLooseElectron->clear();
	M_NumMuons = 0;
	M_MomentumRank->clear();
	M_Pt->clear();
	M_Eta->clear();
	M_Phi->clear();
	M_RelIso->clear();
	M_IsTightMuon->clear();
	M_IsLooseMuon->clear();
	J_NumJets = 0;
	J_MomentumRank->clear();
	J_Pt->clear();
	J_Eta->clear();
	J_Phi->clear();
	J_combSecVtxBTag->clear();
	J_combSecVtxLooseBTag->clear();
	J_combSecVtxMediumBTag->clear();
	J_combSecVtxTightBTag->clear();
	TTE_NumTaus = 0;
	TTE_NumElectrons = 0;
	TTE_NumCombos = 0;
	TTE_MomentumRank->clear();
	TTE_Tau1MomentumRank->clear();
	TTE_Tau1Pt->clear();
	TTE_Tau1Eta->clear();
	TTE_Tau1Phi->clear();
	TTE_Tau1NProngs->clear();
	TTE_Tau1NSignalGammas->clear();
	TTE_Tau1NSignalNeutrals->clear();
	TTE_Tau1DecayMode->clear();
	TTE_Tau1EmFraction->clear();
	TTE_Tau1IsInTheCracks->clear();
	TTE_Tau1HPSagainstElectronLoose->clear();
	TTE_Tau1HPSagainstElectronMVA->clear();
	TTE_Tau1HPSagainstElectronMedium->clear();
	TTE_Tau1HPSagainstElectronTight->clear();
	TTE_Tau1HPSagainstMuonLoose->clear();
	TTE_Tau1HPSagainstMuonMedium->clear();
	TTE_Tau1HPSagainstMuonTight->clear();
	TTE_Tau1HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
	TTE_Tau1HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
	TTE_Tau1HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
	TTE_Tau1HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
	TTE_Tau1HPSdecayModeFinding->clear();
	TTE_Tau1LTPt->clear();
	TTE_Tau1Charge->clear();
	TTE_Tau1LTvalid->clear();
	TTE_Tau1LTIpVtdxy->clear();
	TTE_Tau1LTIpVtdz->clear();
	TTE_Tau1LTIpVtdxyError->clear();
	TTE_Tau1LTIpVtdzError->clear();
	TTE_Tau1LTvx->clear();
	TTE_Tau1LTvy->clear();
	TTE_Tau1LTvz->clear();
	TTE_Tau1LTValidHits->clear();
	TTE_Tau1LTNormChiSqrd->clear();
	TTE_Tau1MatchesGenHadTauFromH1->clear();
	TTE_Tau1MatchesGenHadTauFromH2->clear();
	TTE_Tau1MatchesGenHadTauFromW1->clear();
	TTE_Tau1MatchesGenHadTauFromW2->clear();
	TTE_Tau2MomentumRank->clear();
	TTE_Tau2Pt->clear();
	TTE_Tau2Eta->clear();
	TTE_Tau2Phi->clear();
	TTE_Tau2NProngs->clear();
	TTE_Tau2NSignalGammas->clear();
	TTE_Tau2NSignalNeutrals->clear();
	TTE_Tau2DecayMode->clear();
	TTE_Tau2EmFraction->clear();
	TTE_Tau2IsInTheCracks->clear();
	TTE_Tau2HPSagainstElectronLoose->clear();
	TTE_Tau2HPSagainstElectronMVA->clear();
	TTE_Tau2HPSagainstElectronMedium->clear();
	TTE_Tau2HPSagainstElectronTight->clear();
	TTE_Tau2HPSagainstMuonLoose->clear();
	TTE_Tau2HPSagainstMuonMedium->clear();
	TTE_Tau2HPSagainstMuonTight->clear();
	TTE_Tau2HPSbyLooseCombinedIsolationDeltaBetaCorr->clear();
	TTE_Tau2HPSbyMediumCombinedIsolationDeltaBetaCorr->clear();
	TTE_Tau2HPSbyTightCombinedIsolationDeltaBetaCorr->clear();
	TTE_Tau2HPSbyVLooseCombinedIsolationDeltaBetaCorr->clear();
	TTE_Tau2HPSdecayModeFinding->clear();
	TTE_Tau2LTPt->clear();
	TTE_Tau2Charge->clear();
	TTE_Tau2LTvalid->clear();
	TTE_Tau2LTIpVtdxy->clear();
	TTE_Tau2LTIpVtdz->clear();
	TTE_Tau2LTIpVtdxyError->clear();
	TTE_Tau2LTIpVtdzError->clear();
	TTE_Tau2LTvx->clear();
	TTE_Tau2LTvy->clear();
	TTE_Tau2LTvz->clear();
	TTE_Tau2LTValidHits->clear();
	TTE_Tau2LTNormChiSqrd->clear();
	TTE_Tau2MatchesGenHadTauFromH1->clear();
	TTE_Tau2MatchesGenHadTauFromH2->clear();
	TTE_Tau2MatchesGenHadTauFromW1->clear();
	TTE_Tau2MatchesGenHadTauFromW2->clear();
	TTE_ElectronMomentumRank->clear();
	TTE_ElectronPt->clear();
	TTE_ElectronEta->clear();
	TTE_ElectronPhi->clear();
	TTE_ElectronRelIso->clear();
	TTE_ElectronIsLooseElectron->clear();
	TTE_ElectronIsTightElectron->clear();
	TTE_DitauVisibleMass->clear();
	TTE_DitauMETMass->clear();
	TTE_DitauCosDeltaPhi->clear();
	TTE_DitauDeltaR->clear();
	TTE_Tau1ElectronDeltaR->clear();
	TTE_Tau2ElectronDeltaR->clear();
	TTE_HT->clear();
	TTE_NumCSVLbtagJets->clear();
	TTE_NumCSVMbtagJets->clear();
	TTE_NumCSVTbtagJets->clear();
	TTE_NumNonCSVLbtagJets->clear();
	TTE_NumNonCSVMbtagJets->clear();
	TTE_NumNonCSVTbtagJets->clear();
